#!/bin/bash

B1=`cat ../QUERIES/b_total_rides_info`
NEW_FILES=`cat ../QUERIES/Deduplication_logic_new_CSV_files`

#[--------------------------------]
echo "Updating raw data files..."
psql -U wester -d postgres -c "$NEW_FILES"

echo "CREATING MAIN TABLE..."
psql -U wester -d postgres -c "$B1"
#[--------------------------------]
# section sends queries to postgres database to update the main table

echo "Main table ready"
echo "run executable could be used for data analysing"
