#!/bin/bash

B1=`cat ../QUERIES/b_total_rides_info`
echo "Updating raw data files..."
# pwd | tr -d '\n'> tmp
NEW_FILES=`cat ../QUERIES/Deduplication_logic_new_CSV_files`
# echo "$NEW_FILES"
psql -U wester -d postgres -c "$NEW_FILES"

echo "CREATING MAIN TABLE..."
psql -U wester -d postgres -c "$B1"

echo "Main table ready"
echo "run executable could be used for data analysing"
